### ISSUE TITLE
Using space in encoding is weird

### ISSUE THREAD

**Issue by CMn1yes** [RyanLandDev/DFSchematics#5]
In the DF code template, SplitString is used and has the feature "Leading and trailing spaces are removed from the result." So using "a(space)" will be converted to "a", using a different block. This is a **problem** for big files.

This can be fixed by removing or changing the space character in the encoding code, or as a temporary solution to replace all space characters to another character (not used in encoding) and splitting that and then changing it back when looping the list.

**Comment by ryandev2** [comment]
Thank you for the report, I wasn't aware of this.
I'll proceed by simply removing the space character from the character set. Will be in the next update along with custom head and sign text support.

Beware, this will cause backwards compatibility problems: new schematics will need to use the new builder, otherwise they may have a chance of malfunctioning.
